### ISSUE TITLE
Are the features composition-based or structure-based?

### ISSUE THREAD

**Issue by sgbaird** [janosh/thermo#16]
I.e. chemical formulas vs. CIF files

**Comment by janosh** [comment]
We didn't have structures for most things in the training set so chose to work with the [Magpie feature set](https://nature.com/articles/npjcompumats201628). We also tried out Roost but found that our ~1e3 data points were insufficient for it to learn more powerful than hand-curated features. Roost usually takes around 1e4 data points before it starts to shine.
